[package]
name = "internal_types"
version = "0.1.0"
authors = ["Andrew Lamb <andrew@nerdnetworks.org>"]
edition = "2021"
description = "InfluxDB IOx internal types, shared between IOx instances"
readme = "README.md"

[dependencies]
parking_lot = "0.12"
time = { path = "../time" }
tokio = { version = "1.13", features = ["parking_lot", "sync"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
futures = "0.3"
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt", "rt-multi-thread", "sync", "time"] }
