# This config file aims to replicate the data produced by the capwrite tool:
# https://github.com/influxdata/idpe/tree/e493a8e9b6b773e9374a8542ddcab7d8174d320d/performance/capacity/write
name = "cap_write"
base_seed = "correct horse battery staple"

[[agents]]
name = "cap_write_{{agent_id}}"
count = 2000
sampling_interval = 1

[[agents.measurements]]
name = "cpu"

    # [[agents.measurements.tags]]
    # name = "tag_a_1"
    # value = "host-{{agent_id}}"

    # [[agents.measurements.tags]]
    # name = "tag_a_2"
    # value = "host-{{agent_id}}"

    # [[agents.measurements.tags]]
    # name = "tag_a_3"
    # value = "host-{{agent_id}}"

    # [[agents.measurements.fields]]
    # name = "tag_b_1"
    # pattern = "prefix_{{format-time \"%Y-%m-%d %H:%M\"}}_suffix"

    # [[agents.measurements.fields]]
    # name = "tag_b_2"
    # pattern = "prefix_{{format-time \"%Y-%m-%d %H:%M\"}}_suffix"

    # [[agents.measurements.fields]]
    # name = "tag_b_3"
    # pattern = "prefix_{{format-time \"%Y-%m-%d %H:%M\"}}_suffix"

    # [[agents.measurements.fields]]
    # name = "tag_c_1"
    # pattern = "prefix_{{random 10}}_suffix"

    # [[agents.measurements.fields]]
    # name = "tag_c_2"
    # pattern = "prefix_{{random 10}}_suffix"

    # [[agents.measurements.fields]]
    # name = "tag_c_3"
    # pattern = "prefix_{{random 10}}_suffix"

    # [[agents.measurements.fields]]
    # name = "tag_c_4"
    # pattern = "prefix_{{random 10}}_suffix"

    [[agents.measurements.fields]]
    name = "tag_d_1"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_2"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_3"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_4"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_5"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_6"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_7"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_8"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_9"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_10"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_11"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_12"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_13"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_14"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_15"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_16"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_17"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_18"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_19"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "tag_d_20"
    pattern = "{{random 1}}"

    [[agents.measurements.fields]]
    name = "field_a"
    f64_range = [0.0, 8.0]
