# https://doc.rust-lang.org/cargo/reference/config.html

[cargo-new]
vcs = "git"

[build]
rustflags = ["-C", "target-cpu=native"]

# https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles
#
# Thin LTO does limited cross-crate LTO with compile time being "close" to
# non-LTO builds.
# 
# 	http://blog.llvm.org/2016/06/thinlto-scalable-and-incremental-lto.html
#
[profile.release]
lto = "thin"

[profile.bench]
lto = "thin"
debug = true

# Faster dev builds leaving the debug symbols in the target dir.
#
# Debug symbols will not resolve if the binary is moved!
#
# https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"
incremental = false

[profile.test]
split-debuginfo = "unpacked"
incremental = false

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]