[package]
name = "job_registry"
version = "0.1.0"
authors = ["pauldix <paul@pauldix.net>"]
edition = "2021"

[dependencies] # In alphabetical order
data_types = { path = "../data_types" }
metric = { path = "../metric" }
parking_lot = "0.12"
time = { path = "../time" }
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tracker = { path = "../tracker" }
workspace-hack = { path = "../workspace-hack"}
